name: 📃 New Blog Post
description: Create an issue to add create a new blog post.
title: "📃New Blog Post - "
labels: ['📃new blog post']
body:
- type: textarea
  attributes:
    label: Description
    description: A description of the new blog post.
  validations:
    required: true

- type: textarea
  attributes:
    label: Acceptance Criteria
    description: The items to complete in order to satisfy the Definition of Done.
  validations:
    required: true
    render: markdown

- type: textarea
  attributes:
    label: ToDo Items
    description: Complete the following items before requesting a PR review.
    value: |
      ### The items to complete to satisfy the Definition of Done.
      - [ ] Issue linked to the correct project _(if applicable)_.
      - [ ] Draft pull request created and linked to this issue _(only required with code changes)_.
  validations:
    required: true
    render: markdown

- type: checkboxes
  id: terms
  attributes:
    label: Code of Conduct
    description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/KinsonDigital/.github/blob/master/docs/CODE_OF_CONDUCT.md).
    options:
      - label: I agree to follow this project's Code of Conduct.
        required: true
