name: 🤖Add New Issue To Project


defaults:
  run:
    shell: pwsh


on:
  pull_request_target:
    types: opened
    branches: [main, preview, renovate/*]


jobs:
  add_new_issue_to_project:
    name: Add New Issue
    uses: KinsonDigital/Infrastructure/.github/workflows/add-item-to-project.yml@v13.6.2
    with:
      org-name: "${{ vars.ORGANIZATION_NAME }}"
      org-project-name: "${{ vars.ORG_PROJECT_NAME }}"
      repo-name: "${{ vars.PROJECT_NAME }}"
      item-number: ${{ github.event.pull_request.number }}
    secrets:
      cicd-pat: ${{ secrets.CICD_TOKEN }}
