name: ✅🤖Sync Bot & Status Check


defaults:
  run:
    shell: pwsh


on:
  issues:
    types: [labeled, unlabeled, assigned, unassigned, milestoned, demilestoned]
  pull_request:
    branches: [main, preview]


jobs:
  sync_bot_issue_change:
    name: Sync Bot (Issue Change)
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Set Up Deno
        if: startsWith(github.ref_name, 'feature/')
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run Sync Bot (Issue Change)
        if: startsWith(github.ref_name, 'feature/')
        run: |
          $scriptUrl = "${{ vars.SCRIPT_BASE_URL }}/${{ vars.CICD_SCRIPTS_VERSION }}/${{ vars.SCRIPT_RELATIVE_DIR_PATH}}/sync-bot-status-check.ts";

          $issueNumber = "${{ github.event.issue.number }}";

          echo "Project Name: ${{ vars.PROJECT_NAME }}";
          echo "Issue: $issueNumber";

          if ($manuallyExecuted -and $issueNumber -eq "0") {
            echo "The issue or PR number must be a value greater than 0.";
            exit 1;
          }

          deno run `
            --allow-net `
            "$scriptUrl" `
            "${{ vars.PROJECT_NAME }}" `
            "$issueNumber" `
            "issue" `
            "${{ secrets.CICD_REST_API }}";


  status_check:
    name: Sync Status Check
    if: (github.event_name == 'pull_request' && startsWith(github.head_ref, 'feature/'))
    runs-on: ubuntu-latest
    steps:
      - name: Set Up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run Sync Status Check
        run: |
          $scriptUrl = "${{ vars.SCRIPT_BASE_URL }}/${{ vars.CICD_SCRIPTS_VERSION }}/${{ vars.SCRIPT_RELATIVE_DIR_PATH}}/sync-bot-status-check.ts";

          $eventName = "${{ github.event_name }}";
          $prNumber = "${{ github.event.number }}";

          echo "Event Name: $eventName";
          echo "Project Name: ${{ vars.PROJECT_NAME }}";
          echo "PR Number: $prNumber";
          echo "Event Type: pr";

          if ($manuallyExecuted -and $prNumber -eq "0") {
            echo "The issue or PR number must be a value greater than 0.";
            exit 1;
          }

          deno run `
            --allow-net `
            "$scriptUrl" `
            "${{ vars.PROJECT_NAME }}" `
            "$prNumber" `
            "pr" `
            "${{ secrets.CICD_REST_API }}";
